// Ejercicio 1:
// for (let index = 1; index < 50; index++) {
//     if (index % 2 == 1) {
//         console.log("Números impares " + index)
//     } 
// }
// Ejercicio 2:
// var num = prompt("Digita un número para mostrar tus Pokemones por multiplo de 5")
// const pokemons = 
// [ 'bulbasaur',
//   'ivysaur',
//   'venusaur',
//   'charmander',
//   'charmeleon',
//   'charizard',
//   'squirtle',
//   'wartortle',
//   'blastoise',
//   'caterpie',
//   'metapod',
//   'butterfree',
//   'weedle',
//   'kakuna',
//   'beedrill',
//   'pidgey',
//   'pidgeotto',
//   'pidgeot',
//   'rattata',
//   'raticate',
//   'spearow',
//   'fearow',
//   'ekans',
//   'arbok',
//   'pikachu',
//   'raichu',
//   'sandshrew',
//   'sandslash',
//   'nidoran-f',
//   'nidorina',
//   'nidoqueen',
//   'nidoran-m',
//   'nidorino',
//   'nidoking',
//   'clefairy',
//   'clefable',
//   'vulpix',
//   'ninetales',
//   'jigglypuff',
//   'wigglytuff',
//   'zubat',
//   'golbat',
//   'oddish',
//   'gloom',
//   'vileplume',
//   'paras',
//   'parasect',
//   'venonat',
//   'venomoth',
//   'diglett',
//   'dugtrio',
//   'meowth',
//   'persian',
//   'psyduck',
//   'golduck',
//   'mankey',
//   'primeape',
//   'growlithe',
//   'arcanine',
//   'poliwag',
//   'poliwhirl',
//   'poliwrath',
//   'abra',
//   'kadabra',
//   'alakazam',
//   'machop',
//   'machoke',
//   'machamp',
//   'bellsprout',
//   'weepinbell',
//   'victreebel',
//   'tentacool',
//   'tentacruel',
//   'geodude',
//   'graveler',
//   'golem',
//   'ponyta',
//   'rapidash',
//   'slowpoke',
//   'slowbro',
//   'magnemite',
//   'magneton',
//   'farfetchd',
//   'doduo',
//   'dodrio',
//   'seel',
//   'dewgong',
//   'grimer',
//   'muk',
//   'shellder',
//   'cloyster',
//   'gastly',
//   'haunter',
//   'gengar',
//   'onix',
//   'drowzee',
//   'hypno',
//   'krabby',
//   'kingler',
//   'voltorb' ]
//   for (let index = 0; index < num; index= index + 5) {
//     console.log(pokemons[index])
//   }
// Ejercicio 3:
const arr = [4,"dos",8,"tres",5,9,1,"cero"];

for (let index = 0; index <= arr.length; index++) {
    if( typeof arr[index]=== 'number'){
        console.log(arr[index]+ 'es un número')
    }
}
